name: Generate Snake Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        # Ensure you use the latest version that supports Node.js 20 or later

      # Generate snake game SVG
      - name: Generate snake game
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: 'dist/github-contribution-grid-snake.svg'
          # This ensures the output is generated at the specified location

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        # Update to a version supporting Node.js 20 as available
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Ensure GitHub token is set in your repository secrets for authentication
